name: 'Get & Cache Dependencies'
description: 'Get the npm dependencies and cache them'
inputs:
  disable-cache:
    description: 'Disable caching'
    required: false
    default: 'false'
outputs:
  cache-used:
    description: 'If it did use cache'
    value: ${{ steps.install.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.disable-cache != 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.disable-cache == 'true'
      run: |
        npm ci
        echo cache='${{ inputs.disable-cache != 'true' }}' >> $GITHUB_OUTPUT
      shell: bash