name: 'Get & Cache Dependencies'
description: 'Get the npm dependencies and cache them'
inputs:
  disable-cache:
    description: 'Disable caching'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.disable-cache != 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.disable-cache == 'true'
      run: npm ci
      shell: bash